name: Run Tests

on:
  push:
    branches:
      - dev
    paths-ignore:
      - .github/workflows/run_tests.yaml
  pull_request:
    branches:
      - dev
      - main
    paths-ignore:
      - .github/workflows/run_tests.yaml

jobs:

  run-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
      - run: flutter --version
      - run: flutter pub get

      - name: Run test
        run: flutter test